[package]
name = "ifaddrs-sys"
version = "0.1.0"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
homepage = "https://maidsafe.net"
license = "GPL-3.0"
links = "ifaddrs"
build = "build.rs"

[lib]
name = "ifaddrs_sys"
path = "lib.rs"

[dependencies]
libc = "~0.2.28"

[build-dependencies]
gcc = "0.3"
